import { defineConfig } from "oxlint";

export default defineConfig({
  env: {
    es2025: true,
  },
  ignorePatterns: ["**/node_modules/", "**/dist/", "**/build/", "**/.next/", "**/out/"],
  options: {
    typeAware: true,
  },
  categories: {
    correctness: "warn",
    perf: "warn",
    suspicious: "warn",
    pedantic: "off",
    style: "off",
    restriction: "off",
    nursery: "off",
  },
  plugins: ["import", "eslint", "oxc", "typescript", "unicorn"],
  rules: {
    "capitalized-comments": "off",
    curly: ["error", "all"],
    "id-length": "off",
    "import/no-duplicates": "error",
    "import/no-named-as-default": "warn",
    "import/no-named-as-default-member": "warn",
    "max-statements": "off",
    "no-array-constructor": "error",
    "no-await-in-loop": "error",
    "no-case-declarations": "error",
    "no-empty": "error",
    "no-fallthrough": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-unassigned-import": ["warn", { allow: ["**/*.css"] }],
    "no-unexpected-multiline": "off",
    "no-unused-expressions": "error",
    "no-useless-call": "error",
    "no-underscore-dangle": "off",
    "no-useless-assignment": "off",
    "no-var": "error",
    "one-var": "off",
    "oxc/no-accumulating-spread": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "typescript/ban-ts-comment": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "warn",
    "typescript/no-namespace": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/no-unused-vars": [
      "warn",
      {
        argsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        ignoreRestSiblings: true,
        varsIgnorePattern: "^_",
      },
    ],
    "typescript/prefer-as-const": "error",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/no-empty-file": "off",
    "unicorn/prefer-array-find": "error",
    "unicorn/prefer-set-has": "error",
  },
  overrides: [
    {
      files: ["./backend/**/*", "./types/**/*"],
      env: {
        es2025: true,
        node: true,
      },
      plugins: ["node"],
    },
    {
      files: ["./frontend/**/*"],
      env: {
        es2025: true,
        browser: true,
        "shared-node-browser": true,
      },
      plugins: ["react", "react-perf", "nextjs"],
    },
  ],
});
